@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed May 10 16:52:02 +0300 2023
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim write_s2mm_behav -key {Behavioral:sim_1:Functional:write_s2mm} -tclbatch write_s2mm.tcl -protoinst "protoinst_files/bd_4ed7.protoinst" -protoinst "protoinst_files/bd_09cb.protoinst" -protoinst "protoinst_files/microblaze_top.protoinst" -log simulate.log"
call xsim  write_s2mm_behav -key {Behavioral:sim_1:Functional:write_s2mm} -tclbatch write_s2mm.tcl -protoinst "protoinst_files/bd_4ed7.protoinst" -protoinst "protoinst_files/bd_09cb.protoinst" -protoinst "protoinst_files/microblaze_top.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
