# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/fpga_projects/xilinx/nexys_sdcard/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_clk_wiz_0_1/microblaze_top_clk_wiz_0_1.xci
# IP: The module: 'microblaze_top_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga_projects/xilinx/nexys_sdcard/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_clk_wiz_0_1/microblaze_top_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_top_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/fpga_projects/xilinx/nexys_sdcard/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_clk_wiz_0_1/microblaze_top_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_top_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/fpga_projects/xilinx/nexys_sdcard/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_clk_wiz_0_1/microblaze_top_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_top_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/fpga_projects/xilinx/nexys_sdcard/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_clk_wiz_0_1/microblaze_top_clk_wiz_0_1.xci
# IP: The module: 'microblaze_top_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga_projects/xilinx/nexys_sdcard/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_clk_wiz_0_1/microblaze_top_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_top_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/fpga_projects/xilinx/nexys_sdcard/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_clk_wiz_0_1/microblaze_top_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_top_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/fpga_projects/xilinx/nexys_sdcard/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_clk_wiz_0_1/microblaze_top_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_top_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
