# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.cache/wt [current_project]
set_property parent.project_path C:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {C:/Users/vdyakova/AppData/Roaming/Xilinx/Vivado/2019.2/xhub/board_store} [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_repo_paths {
  c:/.Xilinx/Coregen/CoreLicenses/PmodSD-19.1-A7100.xpr/PmodSD-19.1-A7100/PmodSD-19.1-A7100.ipdefs/GitHubMaterial_0
  c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/ip_repo
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/hdl/microblaze_top_wrapper.vhd
add_files C:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/microblaze_top.bd
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_microblaze_0_1/microblaze_top_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_microblaze_0_1/microblaze_top_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_microblaze_0_1/microblaze_top_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_microblaze_0_axi_intc_0/microblaze_top_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_microblaze_0_axi_intc_0/microblaze_top_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_microblaze_0_axi_intc_0/microblaze_top_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_mdm_1_0/microblaze_top_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_mdm_1_0/microblaze_top_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_mig_7series_0_1/microblaze_top_mig_7series_0_1/user_design/constraints/microblaze_top_mig_7series_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_mig_7series_0_1/microblaze_top_mig_7series_0_1/user_design/constraints/microblaze_top_mig_7series_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_mig_7series_0_1/microblaze_top_mig_7series_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_clk_wiz_0_1/microblaze_top_clk_wiz_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_clk_wiz_0_1/microblaze_top_clk_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_clk_wiz_0_1/microblaze_top_clk_wiz_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_ethernetlite_0_1/microblaze_top_axi_ethernetlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_ethernetlite_0_1/microblaze_top_axi_ethernetlite_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_ethernetlite_0_1/microblaze_top_axi_ethernetlite_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_ethernetlite_0_1/microblaze_top_axi_ethernetlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_uartlite_0_1/microblaze_top_axi_uartlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_uartlite_0_1/microblaze_top_axi_uartlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_uartlite_0_1/microblaze_top_axi_uartlite_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_timer_0_0/microblaze_top_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_timer_0_0/microblaze_top_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_mii_to_rmii_0_1/microblaze_top_mii_to_rmii_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_mii_to_rmii_0_1/microblaze_top_mii_to_rmii_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_rst_clk_wiz_0_100M_0/microblaze_top_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_rst_clk_wiz_0_100M_0/microblaze_top_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_rst_clk_wiz_0_100M_0/microblaze_top_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_1/bd_4ed7_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_1/bd_4ed7_psr0_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_2/bd_4ed7_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_2/bd_4ed7_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_3/bd_4ed7_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_3/bd_4ed7_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_4/bd_4ed7_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_5/bd_4ed7_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_6/bd_4ed7_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_7/bd_4ed7_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_8/bd_4ed7_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_12/bd_4ed7_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_13/bd_4ed7_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_14/bd_4ed7_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_15/bd_4ed7_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_16/bd_4ed7_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_17/bd_4ed7_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_21/bd_4ed7_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_22/bd_4ed7_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_23/bd_4ed7_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_27/bd_4ed7_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_28/bd_4ed7_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_29/bd_4ed7_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_33/bd_4ed7_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_34/bd_4ed7_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_35/bd_4ed7_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_36/bd_4ed7_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_37/bd_4ed7_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_38/bd_4ed7_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_39/bd_4ed7_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_40/bd_4ed7_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_41/bd_4ed7_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/bd_0/ip/ip_42/bd_4ed7_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_rst_mig_7series_0_81M_0/microblaze_top_rst_mig_7series_0_81M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_rst_mig_7series_0_81M_0/microblaze_top_rst_mig_7series_0_81M_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_rst_mig_7series_0_81M_0/microblaze_top_rst_mig_7series_0_81M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_quad_spi_0_0/microblaze_top_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_quad_spi_0_0/microblaze_top_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_quad_spi_0_0/microblaze_top_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_quad_spi_0_0/microblaze_top_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_dlmb_v10_0/microblaze_top_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_dlmb_v10_0/microblaze_top_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_ilmb_v10_0/microblaze_top_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_ilmb_v10_0/microblaze_top_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_dlmb_bram_if_cntlr_0/microblaze_top_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_ilmb_bram_if_cntlr_0/microblaze_top_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_lmb_bram_0/microblaze_top_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_fifo_mm_s_0_0/microblaze_top_axi_fifo_mm_s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_fifo_mm_s_1_0/microblaze_top_axi_fifo_mm_s_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_xbar_0/microblaze_top_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_gpio_0_1/microblaze_top_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_gpio_0_1/microblaze_top_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_gpio_0_1/microblaze_top_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_dma_0_0/microblaze_top_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_dma_0_0/microblaze_top_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_dma_0_0/microblaze_top_axi_dma_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_system_ila_0_1/bd_0/ip/ip_0/bd_09cb_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_system_ila_0_1/bd_0/bd_09cb_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_system_ila_0_1/microblaze_top_system_ila_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_vio_0_0/microblaze_top_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_vio_0_0/microblaze_top_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/microblaze_top_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_microblaze_0_1/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/constrs_1/new/eth.xdc
set_property used_in_implementation false [get_files C:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/constrs_1/new/eth.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top microblaze_top_wrapper -part xc7a100tcsg324-1 -directive AreaOptimized_medium -control_set_opt_threshold 1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef microblaze_top_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file microblaze_top_wrapper_utilization_synth.rpt -pb microblaze_top_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
