# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_gpio_0_1/microblaze_top_axi_gpio_0_1.xci
# IP: The module: 'microblaze_top_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_gpio_0_1/microblaze_top_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_top_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_gpio_0_1/microblaze_top_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_top_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_gpio_0_1/microblaze_top_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_top_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_gpio_0_1/microblaze_top_axi_gpio_0_1.xci
# IP: The module: 'microblaze_top_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_gpio_0_1/microblaze_top_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_top_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_gpio_0_1/microblaze_top_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_top_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/work/Xilinx_lab/DMA_btn_nex_prj_2/nexys_lin_true_sd19/nexys_lin.srcs/sources_1/bd/microblaze_top/ip/microblaze_top_axi_gpio_0_1/microblaze_top_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_top_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
